/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/designer/v1/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Catalogue
         * @description Return the fields a data provider can deliver.
         *
         *     The editor binds values against this list, so a field key cannot be
         *     mistyped. `CatalogueField` is the shape `edutap.pass_builder` already
         *     defines; nothing new is invented here.
         */
        get: operations["list_catalogue_designer_v1_catalogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designer/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Draft
         * @description Return the three artefacts, refusing a draft that carries errors.
         */
        post: operations["export_draft_designer_v1_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designer/v1/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Families
         * @description Return every pass family, with the head fields its form needs.
         */
        get: operations["list_families_designer_v1_families_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designer/v1/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Artefacts
         * @description Return the draft that would export to the given class and object.
         */
        post: operations["import_artefacts_designer_v1_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designer/v1/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Personas
         * @description Return the preview personas, generated from the loaded catalogue.
         */
        get: operations["list_personas_designer_v1_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designer/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Draft
         * @description Return every problem with a draft, without exporting anything.
         */
        post: operations["validate_draft_designer_v1_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BarcodeSection
         * @description Text above and below the code area on the front of the card.
         *
         *     Google offers three slots; two above the code and one below it.
         */
        BarcodeSection: {
            first_bottom?: components["schemas"]["Line"] | null;
            first_top?: components["schemas"]["Line"] | null;
            second_top?: components["schemas"]["Line"] | null;
        };
        /**
         * CatalogueErrorResponse
         * @description Body of a `500` caused by a malformed catalogue file on disk.
         *
         *     This is the one case where `500` is the right status: the request itself
         *     was fine, it is the *server's* configuration that is broken. The body
         *     still has to be JSON, and it has to name the offending file so whoever
         *     deployed a bad catalogue can find it.
         */
        CatalogueErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * CatalogueField
         * @description One field a data provider can deliver.
         */
        CatalogueField: {
            /** Description */
            description?: string | null;
            /** Key */
            key: string;
            /** Label */
            label?: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Value Type */
            value_type: string;
        };
        /**
         * Cell
         * @description One column of a front row, or one entry of the back list.
         *
         *     When both values are set Google renders them as a single element with a
         *     slash between them, and it refuses a second value without a first.
         */
        Cell: {
            first?: components["schemas"]["Line"] | null;
            second?: components["schemas"]["Line"] | null;
        };
        /**
         * Draft
         * @description A complete pass design, independent of Google's structures.
         */
        Draft: {
            /**
             * Back Items
             * @default []
             */
            back_items: components["schemas"]["Cell"][];
            barcode_section?: components["schemas"]["BarcodeSection"] | null;
            /** Family */
            family: string;
            /**
             * Front Rows
             * @default []
             */
            front_rows: components["schemas"]["Row"][];
            /**
             * Head
             * @default {}
             */
            head: {
                [key: string]: string;
            };
            /**
             * Image Modules
             * @default []
             */
            image_modules: components["schemas"]["ImageModuleDraft"][];
            /**
             * Link Modules
             * @default []
             */
            link_modules: components["schemas"]["LinkModuleDraft"][];
            /** @default {} */
            list_view: components["schemas"]["ListView"];
            /**
             * @default {
             *       "redemption_issuers": [],
             *       "smart_tap_enabled": false
             *     }
             */
            redemption: components["schemas"]["RedemptionSettings"];
            /**
             * Text Modules
             * @default []
             */
            text_modules: components["schemas"]["TextModuleDraft"][];
            /**
             * Unmapped
             * @default {}
             */
            unmapped: {
                [key: string]: unknown;
            };
        };
        /**
         * ExportErrorResponse
         * @description Body of a `422`: the findings that blocked an export or an import.
         *
         *     Not FastAPI's generic `HTTPValidationError` — the request body itself was
         *     well-formed, it is the *draft* (or, for `/import`, the artefacts handed
         *     in) that carries errors — so this is declared explicitly via `responses=`
         *     on the route rather than left to the default, which would otherwise
         *     mislead a client generated from the OpenAPI schema.
         */
        ExportErrorResponse: {
            /** Detail */
            detail: components["schemas"]["Finding"][];
        };
        /**
         * ExportRequest
         * @description Body of `POST /export`.
         */
        ExportRequest: {
            /** Class Id */
            class_id: string;
            draft: components["schemas"]["Draft"];
            /** Object Id */
            object_id: string;
        };
        /**
         * ExportResponse
         * @description Body of the `/export` response: the three artefacts.
         */
        ExportResponse: {
            /** Class Json */
            class_json: {
                [key: string]: unknown;
            };
            /** Mappings */
            mappings: {
                [key: string]: unknown;
            };
            /** Object Json */
            object_json: {
                [key: string]: unknown;
            };
        };
        /**
         * FamilyResponse
         * @description Body of one entry in the `/families` response.
         */
        FamilyResponse: {
            /** Family Id */
            family_id: string;
            /** Head Fields */
            head_fields: components["schemas"]["HeadField"][];
            /** Label */
            label: string;
            /** Required On Create */
            required_on_create: string[];
        };
        /**
         * FieldRef
         * @description One reference in a fallback chain.
         */
        FieldRef: {
            /** Date Format */
            date_format?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "image";
            /** Module Id */
            module_id: string;
        };
        /**
         * Finding
         * @description One problem with a draft, in the language the caller asked for.
         */
        Finding: {
            /** Location */
            location: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadField
         * @description One field of a family's head section.
         */
        HeadField: {
            /**
             * Choices
             * @default []
             */
            choices: string[];
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "localized_text" | "image_uri" | "colour" | "enum";
            /** Label */
            label: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Scope
             * @default class
             * @enum {string}
             */
            scope: "class" | "object";
        };
        /**
         * ImageModuleDraft
         * @description One image module. `uri` is exported; local previews never are.
         */
        ImageModuleDraft: {
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Module Id */
            module_id: string;
            /**
             * Uri
             * @default
             */
            uri: string;
        };
        /**
         * ImportErrorResponse
         * @description Body of a `400`: an unknown or empty pass family, as plain text.
         */
        ImportErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ImportRequest
         * @description Body of `POST /import`.
         */
        ImportRequest: {
            /** Class Json */
            class_json: {
                [key: string]: unknown;
            };
            /** Family */
            family: string;
            /** Object Json */
            object_json: {
                [key: string]: unknown;
            };
        };
        /**
         * Line
         * @description A displayed value.
         *
         *     `fallback_chain` is a list of things to *try*, not a list of things to
         *     show: Google displays the first reference that points at a non-empty
         *     field. This is how one template serves several kinds of person.
         */
        Line: {
            /** Fallback Chain */
            fallback_chain: components["schemas"]["FieldRef"][];
        };
        /**
         * LinkModuleDraft
         * @description One entry of the link block on the back of the pass.
         */
        LinkModuleDraft: {
            /** Description */
            description?: string | null;
            /** Uri */
            uri: string;
        };
        /**
         * ListView
         * @description The two rows of the Wallet overview entry.
         *
         *     `thirdRowOption` is deprecated upstream and is not modelled here.
         */
        ListView: {
            /** First Row */
            first_row?: components["schemas"]["Line"] | components["schemas"]["TransitOption"] | null;
            second_row?: components["schemas"]["Line"] | null;
        };
        /**
         * Persona
         * @description One preview person: coherent, fictional, reproducible.
         */
        Persona: {
            /** Gender */
            gender: string;
            /** Label */
            label: string;
            /** Locale */
            locale: string;
            /** Persona Id */
            persona_id: string;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * RedemptionSettings
         * @description How the pass is redeemed: over NFC, visually, or both.
         */
        RedemptionSettings: {
            /** Barcode Type */
            barcode_type?: string | null;
            /** Barcode Value */
            barcode_value?: string | null;
            /**
             * Redemption Issuers
             * @default []
             */
            redemption_issuers: string[];
            /** Redemption Value */
            redemption_value?: string | null;
            /**
             * Smart Tap Enabled
             * @default false
             */
            smart_tap_enabled: boolean;
        };
        /**
         * Row
         * @description A front row: one, two or three cells.
         */
        Row: {
            /** Cells */
            cells: components["schemas"]["Cell"][];
        };
        /**
         * TextModuleDraft
         * @description One text module, either a constant or bound to a provider field.
         */
        TextModuleDraft: {
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Header */
            header?: string | null;
            /** Module Id */
            module_id: string;
            /**
             * Value
             * @default
             */
            value: string;
        };
        /**
         * TransitOption
         * @description The Transit-only alternative to a field reference in the list view.
         */
        TransitOption: {
            /** Option */
            option: string;
        };
        /**
         * ValidateRequest
         * @description Body of `POST /validate`.
         */
        ValidateRequest: {
            draft: components["schemas"]["Draft"];
        };
        /**
         * ValidateResponse
         * @description Body of the `/validate` response.
         */
        ValidateResponse: {
            /** Findings */
            findings: components["schemas"]["Finding"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_catalogue_designer_v1_catalogue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueField"][];
                };
            };
        };
    };
    export_draft_designer_v1_export_post: {
        parameters: {
            query?: never;
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueErrorResponse"];
                };
            };
        };
    };
    list_families_designer_v1_families_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyResponse"][];
                };
            };
        };
    };
    import_artefacts_designer_v1_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportErrorResponse"];
                };
            };
        };
    };
    list_personas_designer_v1_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"][];
                };
            };
        };
    };
    validate_draft_designer_v1_validate_post: {
        parameters: {
            query?: never;
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueErrorResponse"];
                };
            };
        };
    };
}
